### ISSUE TITLE
Passing multiple series

### ISSUE THREAD

**Issue by scottstelljes** [OliverSherouse/bls#15]
How can you pass a list of series ids to the series argument in get_series()?

**Comment by OliverSherouse** [comment]
Thanks for your email, Scott, I can confirm this is a bug and will turn around a fix ASAP.

Details, for the record:

> The help for the function bls.get_series() states that the first argument can be either a series id or a sequence of series ids. I have used the function successfully to return a single series but I get error messages for multiple series. I have tried list and tuple. For example:
>  
> bls.get_series('LAUCN010970000000003', firstyr, lastyr, key = myblskey) returns data.
> bls.get_series('LAUCN010990000000003', firstyr, lastyr, key = myblskey) returns data.
>  
> But the following result in key errors:
> bls.get_series(['LAUCN010970000000003','LAUCN010990000000003'], firstyr, lastyr, key = myblskey)
> bls.get_series(('LAUCN010970000000003','LAUCN010990000000003'), firstyr, lastyr, key = myblskey

**Comment by OliverSherouse** [comment]
Passing a sequence now works with version 0.3, available on pypi.

**Comment by ghost** [comment]
Should I pass a list or a tuple?

**Comment by ghost** [comment]
Never mind. I tried it. It takes lists. Thank you very much for solving this.

**Comment by OliverSherouse** [comment]
For the record, either should work.
