### ISSUE TITLE
Annual averages

### ISSUE THREAD

**Issue by drgrubman** [OliverSherouse/bls#3]
Thanks again for making this! It's really helped me.

The BLS changed their API and now the annual averages aren't included automatically. Is there a way to toggle this in the code?

**Comment by OliverSherouse** [comment]
Since with PR #10 we're now using period indices, the correct approach is to use the [`DataFrame.resample`] method(https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.resample.html)
