### ISSUE TITLE
Passing API Key 

### ISSUE THREAD

**Issue by PFurst2000** [OliverSherouse/bls#32]
I have had a great amount of difficulty passing an API key into my scripts using this package. I have setup the BLS API key as either an environment variable or tried passing into the script but have not had any success. Would you please provide sample code of passing a sample API key into the script in the form of an environment variable and using the getseries method you previously suggested?
Thank you,

**Comment by OliverSherouse** [comment]
Can you give a little more information about what you're trying to do and how it isn't working? (Side note: I'm actually moving this week so if there need to be code updates it might take a bit.)

**Comment by PFurst2000** [comment]
Thanks Oliver, no worries if you need to take some time with this. I had
been having trouble with this but the following solution worked.

registrationkey = ‘EnterAPIKeyHere’
I never figured out how to get the script to pass along the environment
variable saved with the BLS API key. For whatever reason, the same code
works today that hasn't worked all week.


Below is the code I was previously using in a jupyter notebook that
wouldn't recognize the bls API key.
import pandas as pd
import matplotlib as plt
import numpy as np
import bls
registrationkey = ' EnterAPIKeyHere'
FairfieldCountyCT_UnemploymentRate = bls.get_series('LAUCN090010000000003')
LitchfieldCountyCT_UnemploymentRate = bls.get_series('LAUCN090050000000003')
NewHavenCountyCT_UnemploymentRate = bls.get_series('LAUCN090090000000003')
total = pd.merge((pd.merge(FairfieldCountyCT_UnemploymentRate,
LitchfieldCountyCT_UnemploymentRate,  how='inner', on='date')),
NewHavenCountyCT_UnemploymentRate, how='inner', on='date')
total.to_csv (r'C:\Users\usernamehidden\Desktop\BLSTest.csv')
total

**Comment by PFurst2000** [comment]
Yeah so I took a closer look at this and the same code worked fine on a computer with little firewall protection compared with a corporate computer with strong network security. The network security features seemed to be blocking the API key reading for whatever reason.
