### ISSUE TITLE
Requesting current-year releases in a time series

### ISSUE THREAD

**Issue by kraemerd17** [OliverSherouse/bls#5]
I can't tell if this is fundamentally an API problem or something we can solve, but say I want to retrieve the last 12 months of the `LNS14000000` national unemployment rate series. My first thought is to call
```
>>> get_series('LNS14000000')
```
As of writing this, it is March 2017 and there have been two releases for this series in 2017. However, the last entry of the result is 
```
2016-12-01    4.7
```
This suggests to me that the default end year `2017` is cutting off at the start of 2017. If I supply `2018`, the wrapper catches this and sends `2017` anyways. (I've tried just using the API, and supplying `2018` produces an error).

**Comment by OliverSherouse** [comment]
It's an off-by-one error; given no parameters, the wrapper auto-selects an end and start year, but picks years 10 apart, not ten years total. I'll fix and bump the version tonight.

Meanwhile, as a workaround, try `get_series('LNS14000000', start_year=2008)`
